---
- hosts: all
  become: yes
  vars_files:
    - group_vars/all/vault.yml

  tasks:
    - name: Test vault variable
      debug:
        msg: "DB password is {{ db_password }}"

- name: Base OS Hardening with Roles
  hosts: all
  become: true

  roles:
    - ssh_hardening
    - firewall
    - updates
    - crowdsec
    - web_server
    - monitoring
