plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running

keyed_groups:
  - prefix: env
    key: tags.env
  - prefix: role
    key: tags.role

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
